### ISSUE TITLE
Compiling issue: No space left on device

### ISSUE THREAD

**Issue by HernanVM** [jodyhey/IMa3#1]
Dear Jody, I'm having issues compiling IMa3 on two different clusters. I get this following the readme file. What am I missing? I've been able to compile IMa2p fine previously. Thanks, Hernán

`[hernan@login IMa3]$ make
mpicxx alltreestrings.cpp autoc.cpp build_gtree.cpp build_poptree.cpp burnphylogenycounts.cpp calc_prob_data.cpp chainprint.cpp freemem.cpp gewekeIM.cpp ginfo.cpp gtint.cpp histograms.cpp ima_main.cpp initialize.cpp jointfind.cpp marglike.cpp mcmcfile.cpp msdirent.cpp multi_t_bins.cpp output.cpp popmig.cpp readata.cpp readpriorfile.cpp surface_call_functions.cpp surface_search_functions.cpp swapchains.cpp treeprint.cpp update_gtree_common.cpp update_gtree.cpp update_hg.cpp update_mc_params.cpp update_poptree.cpp update_priors.cpp update_t_NW.cpp update_t_RY.cpp update_t_RYhg.cpp utilities.cpp -D MPI_ENABLED -D NDEBUG -o IMa3 -O3 -fpermissive
build_poptree.cpp:782:1: fatal error: error writing to /tmp/ccRWwHz6.s: No space left on device
 }
 ^
compilation terminated.
burnphylogenycounts.cpp:140:1: fatal error: error writing to /tmp/ccRWwHz6.s: No space left on device
 }
 ^
compilation terminated.
calc_prob_data.cpp:916:1: fatal error: error writing to /tmp/ccRWwHz6.s: No space left on device
 }                               /* likelihoodSW */
 ^
compilation terminated.
In file included from chainprint.cpp:15:0:
ima.hpp:1864:32: fatal error: error writing to /tmp/ccRWwHz6.s: No space left on device
 void printgewekez(FILE * outto);
                                ^
compilation terminated.
ima_main.cpp: In function ‘void commit_mpi_updatescalar()’:
ima_main.cpp:4532:3: warning: ‘int MPI_Type_extent(MPI_Datatype, MPI_Aint*)’ is deprecated: MPI_Type_extent is superseded by MPI_Type_get_extent in MPI-2.0 [-Wdeprecated-declarations]
   MPI_Type_extent(MPI_INT,&intex);
   ^~~~~~~~~~~~~~~
In file included from ima.hpp:68:0,
                 from ima_main.cpp:4:
/util/opt/openmpi/1.10.6.psm2/gcc/6.1.0/include/mpi.h:1753:20: note: declared here
 OMPI_DECLSPEC  int MPI_Type_extent(MPI_Datatype type, MPI_Aint *extent)
                    ^~~~~~~~~~~~~~~
ima_main.cpp:4532:33: warning: ‘int MPI_Type_extent(MPI_Datatype, MPI_Aint*)’ is deprecated: MPI_Type_extent is superseded by MPI_Type_get_extent in MPI-2.0 [-Wdeprecated-declarations]
   MPI_Type_extent(MPI_INT,&intex);
                                 ^
In file included from ima.hpp:68:0,
                 from ima_main.cpp:4:
/util/opt/openmpi/1.10.6.psm2/gcc/6.1.0/include/mpi.h:1753:20: note: declared here
 OMPI_DECLSPEC  int MPI_Type_extent(MPI_Datatype type, MPI_Aint *extent)
                    ^~~~~~~~~~~~~~~
ima_main.cpp:4533:3: warning: ‘int MPI_Type_extent(MPI_Datatype, MPI_Aint*)’ is deprecated: MPI_Type_extent is superseded by MPI_Type_get_extent in MPI-2.0 [-Wdeprecated-declarations]
   MPI_Type_extent(MPI_DOUBLE,&doublex);
   ^~~~~~~~~~~~~~~
In file included from ima.hpp:68:0,
                 from ima_main.cpp:4:
/util/opt/openmpi/1.10.6.psm2/gcc/6.1.0/include/mpi.h:1753:20: note: declared here
 OMPI_DECLSPEC  int MPI_Type_extent(MPI_Datatype type, MPI_Aint *extent)
                    ^~~~~~~~~~~~~~~
ima_main.cpp:4533:38: warning: ‘int MPI_Type_extent(MPI_Datatype, MPI_Aint*)’ is deprecated: MPI_Type_extent is superseded by MPI_Type_get_extent in MPI-2.0 [-Wdeprecated-declarations]
   MPI_Type_extent(MPI_DOUBLE,&doublex);
                                      ^
In file included from ima.hpp:68:0,
                 from ima_main.cpp:4:
/util/opt/openmpi/1.10.6.psm2/gcc/6.1.0/include/mpi.h:1753:20: note: declared here
 OMPI_DECLSPEC  int MPI_Type_extent(MPI_Datatype type, MPI_Aint *extent)
                    ^~~~~~~~~~~~~~~
ima_main.cpp:4544:3: warning: ‘int MPI_Type_struct(int, int*, MPI_Aint*, ompi_datatype_t**, ompi_datatype_t**)’ is deprecated: MPI_Type_struct is superseded by MPI_Type_create_struct in MPI-2.0 [-Wdeprecated-declarations]
   MPI_Type_struct(10,mpi_updatescalar_blocklengths,mpi_updatescalar_displacements,mpi_updatescalar_types,&MPI_updatescalar);
   ^~~~~~~~~~~~~~~
In file included from ima.hpp:68:0,
                 from ima_main.cpp:4:
/util/opt/openmpi/1.10.6.psm2/gcc/6.1.0/include/mpi.h:1796:20: note: declared here
 OMPI_DECLSPEC  int MPI_Type_struct(int count, int array_of_blocklengths[],
                    ^~~~~~~~~~~~~~~
ima_main.cpp:4544:123: warning: ‘int MPI_Type_struct(int, int*, MPI_Aint*, ompi_datatype_t**, ompi_datatype_t**)’ is deprecated: MPI_Type_struct is superseded by MPI_Type_create_struct in MPI-2.0 [-Wdeprecated-declarations]
 atescalar_blocklengths,mpi_updatescalar_displacements,mpi_updatescalar_types,&MPI_updatescalar);
                                                                                               ^
In file included from ima.hpp:68:0,
                 from ima_main.cpp:4:
/util/opt/openmpi/1.10.6.psm2/gcc/6.1.0/include/mpi.h:1796:20: note: declared here
 OMPI_DECLSPEC  int MPI_Type_struct(int count, int array_of_blocklengths[],
                    ^~~~~~~~~~~~~~~
make: *** [all] Error 1`

**Comment by jodyhey** [comment]
I have no idea. sounds like a local permission issue
