### ISSUE TITLE
compiling error: ‘MPI_Type_extent’ was not declared in this scope

### ISSUE THREAD

**Issue by apwilder** [jodyhey/IMa3#2]
Hi,
When I try to compile IMa3 in Linux using the make command, I get the following error:

[centos@ima3 IMa3]$ make
mpicxx update_poptree.cpp gewekeIM.cpp update_mc_params.cpp jointfind.cpp marglike.cpp update_t_NW.cpp multi_t_bins.cpp update_t_RY.cpp update_priors.cpp surface_call_functions.cpp treeprint.cpp ima_main.cpp calc_prob_data.cpp surface_search_functions.cpp popmig.cpp utilities.cpp gtint.cpp initialize.cpp build_gtree.cpp output.cpp freemem.cpp mcmcfile.cpp swapchains.cpp burnphylogenycounts.cpp ginfo.cpp build_poptree.cpp readpriorfile.cpp update_gtree.cpp autoc.cpp update_gtree_common.cpp update_t_RYhg.cpp histograms.cpp chainprint.cpp msdirent.cpp readata.cpp alltreestrings.cpp update_hg.cpp -D MPI_ENABLED -D NDEBUG -o IMa3 -O3 -fpermissive
ima_main.cpp: In function ‘void commit_mpi_updatescalar()’:
ima_main.cpp:4540:33: error: ‘MPI_Type_extent’ was not declared in this scope
   MPI_Type_extent(MPI_INT,&intex);
                                 ^
ima_main.cpp:4552:123: error: ‘MPI_Type_struct’ was not declared in this scope
   MPI_Type_struct(10,mpi_updatescalar_blocklengths,mpi_updatescalar_displacements,mpi_updatescalar_types,&MPI_updatescalar);
                                                                                                                           ^
make: *** [all] Error 1

Any ideas?
Thanks for your help,
Aryn

**Comment by jodyhey** [comment]
probably Open MPI is not installed
