### ISSUE TITLE
Compiling IMa3 with Open MPI v4

### ISSUE THREAD

**Issue by PopGen33** [jodyhey/IMa3#3]
I initially tried to compile IMa3 on Ubuntu on WSL and got the following errors:
`mpicxx update_poptree.cpp gewekeIM.cpp update_mc_params.cpp jointfind.cpp marglike.cpp update_t_NW.cpp multi_t_bins.cpp update_t_RY.cpp update_priors.cpp surface_call_functions.cpp treeprint.cpp ima_main.cpp calc_prob_data.cpp surface_search_functions.cpp popmig.cpp utilities.cpp gtint.cpp initialize.cpp build_gtree.cpp output.cpp freemem.cpp mcmcfile.cpp swapchains.cpp burnphylogenycounts.cpp ginfo.cpp build_poptree.cpp readpriorfile.cpp update_gtree.cpp autoc.cpp update_gtree_common.cpp update_t_RYhg.cpp histograms.cpp chainprint.cpp msdirent.cpp readata.cpp alltreestrings.cpp update_hg.cpp -D MPI_ENABLED -D NDEBUG -o IMa3 -O3 -fpermissive
ima_main.cpp:1164:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
 1164 | #endif WRITECHECKOUTPUTPROGRESSDEBUGFILE
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ima_main.cpp:1167:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
 1167 | #endif USELVD
      |        ^~~~~~
In file included from ima.hpp:91,
                 from ima_main.cpp:4:
ima_main.cpp: In function 'void commit_mpi_updatescalar()':
/home/popgen/miniconda3/include/mpi.h:338:73: error: static assertion failed: MPI_Type_extent was removed in MPI-3.0.  Use MPI_Type_get_extent instead.
  338 | #define THIS_FUNCTION_WAS_REMOVED_IN_MPI30(func, newfunc) static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
      |                                                                         ^
/home/popgen/miniconda3/include/mpi.h:2865:31: note: in expansion of macro 'THIS_FUNCTION_WAS_REMOVED_IN_MPI30'
 2865 | #define MPI_Type_extent(...)  THIS_FUNCTION_WAS_REMOVED_IN_MPI30(MPI_Type_extent, MPI_Type_get_extent)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ima_main.cpp:4557:3: note: in expansion of macro 'MPI_Type_extent'
 4557 |   MPI_Type_extent(MPI_INT,&intex);
      |   ^~~~~~~~~~~~~~~
/home/popgen/miniconda3/include/mpi.h:338:73: error: static assertion failed: MPI_Type_extent was removed in MPI-3.0.  Use MPI_Type_get_extent instead.
  338 | #define THIS_FUNCTION_WAS_REMOVED_IN_MPI30(func, newfunc) static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
      |                                                                         ^
/home/popgen/miniconda3/include/mpi.h:2865:31: note: in expansion of macro 'THIS_FUNCTION_WAS_REMOVED_IN_MPI30'
 2865 | #define MPI_Type_extent(...)  THIS_FUNCTION_WAS_REMOVED_IN_MPI30(MPI_Type_extent, MPI_Type_get_extent)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ima_main.cpp:4558:3: note: in expansion of macro 'MPI_Type_extent'
 4558 |   MPI_Type_extent(MPI_DOUBLE,&doublex);
      |   ^~~~~~~~~~~~~~~
/home/popgen/miniconda3/include/mpi.h:338:73: error: static assertion failed: MPI_Type_struct was removed in MPI-3.0.  Use MPI_Type_create_struct instead.
  338 | #define THIS_FUNCTION_WAS_REMOVED_IN_MPI30(func, newfunc) static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
      |                                                                         ^
/home/popgen/miniconda3/include/mpi.h:2869:31: note: in expansion of macro 'THIS_FUNCTION_WAS_REMOVED_IN_MPI30'
 2869 | #define MPI_Type_struct(...)  THIS_FUNCTION_WAS_REMOVED_IN_MPI30(MPI_Type_struct, MPI_Type_create_struct)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ima_main.cpp:4569:3: note: in expansion of macro 'MPI_Type_struct'
 4569 |   MPI_Type_struct(10,mpi_updatescalar_blocklengths,mpi_updatescalar_displacements,mpi_updatescalar_types,&MPI_updatescalar);
      |   ^~~~~~~~~~~~~~~
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1`

After reading through the errors and doing a little research, I realized the problem was that Open MPI v4 no longer accepts the deprecated functions MPI_type_extent and MPI_type_struct ([see this FAQ](https://www.open-mpi.org/faq/?category=mpi-removed)). So, I made the following changes to ima_main.cpp lines 4556-4558:

`MPI_Aint intex,doublex,lb;//Previously: MPI_Aint intex,doublex;
MPI_Type_get_extent(MPI_INT,&lb,&intex);//Previously: MPI_Type_extent(MPI_INT,&intex);
MPI_Type_get_extent(MPI_DOUBLE,&lb,&doublex);//Previously: MPI_Type_extent(MPI_DOUBLE,&doublex);`

...and changed line 4569 to:

`MPI_Type_create_struct(10,mpi_updatescalar_blocklengths,mpi_updatescalar_displacements,mpi_updatescalar_types,&MPI_updatescalar);//Previously: MPI_Type_struct(...)`

I'm not sure if this is the best way to fix it, but this resulted in IMa3 compiling as expected.

I wanted to confirm that these changes don't impact how the program runs. I'm not very familiar with C++, and have no familiarity with programming for MPI, but these changes seem to work and might be applicable to the other issues open on this project. Thanks for your time!

**Comment by jodyhey** [comment]
Thanks for figuring this out.  I've not tested it, but It should be fine. 
Will try it out when I get the chance, and commit if it works

**Comment by PopGen33** [comment]
Thank you!
