### ISSUE TITLE
Problem with priorfile

### ISSUE THREAD

**Issue by rcrvano** [jodyhey/IMa3#5]
Hello!

Can you help me, please? 
IMa3 doesn't work well with my input files.
I have tried a lot of variants and all variants of trees

For example:
for this tree `(0,(1,2)3)4` 
I got `IMa3: error in uppergamma function -  too many iterations within gcflog()`
and same for `(2,(0,1)3)4`

`(1,(0,2)3)` - that starts to work. But it never finished. An infinite loop somewhere in the code

My input string and files below. 
Maybe you can give me some advice on what is wrong with my parameters or I need to specify something additionally?
`IMburn` is disabled

Input string:
`./IMa3 -i IMomuli.txt -o IMomuli.out -b 1.0 -c3 -g priorfile.txt -hn4 -L 10000 -j2 -p7 -r2 -s888 -u10`
[priorfile.txt](https://github.com/jodyhey/IMa3/files/6575422/priorfile.txt)
[IMomuli.txt](https://github.com/jodyhey/IMa3/files/6575423/IMomuli.txt)

**Comment by jodyhey** [comment]
migration priors are way too high.  
the upper bound of migration should be set so that product of migration (m/u) and coalescent rate (4Nu) is not much higher than 1.
